import Foundation
import GRDB

/// Per-meeting "detailed outline" — a time-stamped, topic-segmented
/// readable record of the meeting that sits between the one-page summary
/// and the full transcript on the readability/density spectrum.
///
/// Think of it as: each major topic the conversation covered gets its own
/// section with start/end timestamps, the speakers who participated, a
/// 3–6 sentence prose paragraph capturing the arc of that topic, and an
/// optional bullet list of hard facts (decisions, numbers, open questions).
///
/// Generated by `DetailedOutlineService.generate(...)` after summary
/// completes. Stored as a single Markdown blob keyed by meetingId — one
/// outline per meeting, replaced on regeneration. Mirrors the storage
/// pattern of `CleanedTranscript`.
struct DetailedOutline: Codable, FetchableRecord, MutablePersistableRecord {
    /// Owning meeting id. Primary key — at most one outline per meeting.
    var meetingId: String
    /// The outline body — Markdown with `## [mm:ss – mm:ss] Topic` section
    /// headers, **Speakers** lines, prose paragraphs, optional bullet lists.
    var text: String
    /// When this version was generated.
    var generatedAt: Date
    /// How it was produced: "ai" (LLM pass succeeded) or "ai-failed"
    /// (the call threw or returned malformed Markdown, blob is the
    /// rendered error stub). Used for diagnostics + retry decisions.
    var method: String
    /// Optional model identifier ("claude-sonnet-4-6", "ollama/qwen3:8b",
    /// etc.) so the UI can show provenance and the next regen knows which
    /// backend last produced the blob.
    var modelUsed: String?

    static let databaseTableName = "detailedOutline"

    enum Columns {
        static let meetingId   = Column(CodingKeys.meetingId)
        static let text        = Column(CodingKeys.text)
        static let generatedAt = Column(CodingKeys.generatedAt)
        static let method      = Column(CodingKeys.method)
        static let modelUsed   = Column(CodingKeys.modelUsed)
    }
}
