import CryptoKit
import Foundation
import GRDB

/// Per-meeting "enhanced note" — a derived AI artifact that rewrites the
/// user's raw notes into a polished version while preserving the user's own
/// structure (their headings, their order, their emphasis). The transcript,
/// when present, is used only to correct names and figures and to expand the
/// user's terse bullets — never to impose a new format.
///
/// Kept deliberately distinct from two neighbouring artifacts:
///   - `MeetingNote` is the user's ground truth and is never overwritten by
///     this pass — the enhancement reads it, it doesn't mutate it.
///   - `MeetingSummary` is the fixed TL;DR / Decisions / Action Items digest.
///     The enhanced note is the *opposite*: it mirrors the user's structure
///     rather than imposing the app's.
///
/// Generated by `AppState.generateEnhancedNotesForTask(meetingId:)`, driven by
/// the user-initiated `.enhanceNotes` task type (never auto-enqueued). Stored
/// as a single Markdown blob keyed by meetingId — one per meeting, replaced on
/// re-enhancement. Mirrors the storage pattern of `DetailedOutline`.
struct EnhancedNote: Codable, FetchableRecord, MutablePersistableRecord {
    /// Owning meeting id. Primary key — at most one enhanced note per meeting.
    var meetingId: String
    /// The polished note body — Markdown that keeps the user's headings and
    /// section order, with terse bullets expanded into full sentences and
    /// names/figures corrected against the transcript when one was available.
    var content: String
    /// Optional model identifier ("claude-sonnet-4-…", "ollama/qwen3:8b") so
    /// the UI can show provenance and the next pass knows which backend last
    /// produced the blob.
    var modelUsed: String?
    /// When this version was generated.
    var generatedAt: Date
    /// Stable hash (SHA256) of the combined source notes this enhancement was
    /// built from. The viewer compares it to the *current* combined notes and
    /// offers "Re-enhance" when they diverge. Stored as a hash rather than the
    /// full text to keep the row small. See `EnhancedNote.stableHash(_:)`.
    var sourceNotesHash: String
    /// Character count of the source notes at generation time — a cheap
    /// secondary staleness signal and a useful diagnostic.
    var sourceNotesLength: Int

    static let databaseTableName = "enhancedNote"

    enum Columns {
        static let meetingId         = Column(CodingKeys.meetingId)
        static let content           = Column(CodingKeys.content)
        static let modelUsed         = Column(CodingKeys.modelUsed)
        static let generatedAt       = Column(CodingKeys.generatedAt)
        static let sourceNotesHash   = Column(CodingKeys.sourceNotesHash)
        static let sourceNotesLength = Column(CodingKeys.sourceNotesLength)
    }

    /// Process-stable hash of the source notes. Uses SHA256 (via CryptoKit)
    /// rather than `String.hashValue` — the latter is seeded per process, so
    /// it would produce a different value on every launch and falsely flag
    /// every saved enhancement as stale. The trimmed input means trailing
    /// whitespace edits don't count as a real change.
    static func stableHash(_ notes: String) -> String {
        let normalized = notes.trimmingCharacters(in: .whitespacesAndNewlines)
        let digest = SHA256.hash(data: Data(normalized.utf8))
        return digest.map { String(format: "%02x", $0) }.joined()
    }
}
